### ISSUE TITLE
StructuralPhysical schema v1.0.0 missing bis:PhysicalType subclasses

### ISSUE THREAD

**Issue by diegoalexdiaz** [iTwin/bis-schemas#67]
Every concrete bis:PhysicalElement class in the StructuralPhysical schema shall have a corresponding PhysicalType subclass. E.g. Column --> ColumnType, Beam --> BeamType, etc.

**Comment by NabilSleiman** [comment]
We have the extruded member which can be a column or a beam, should we deprecate that in favor of more specific members?

**Comment by diegoalexdiaz** [comment]
The StructuralPhysical schema (both versions 1.0.0 and 1.1.0) have several concrete-physical-classes (i.e. classes that can be instantiated). That schema needs to provide corresponding PhysicalType-classes so connectors/iModel-writers can setup the expected PhysicalElement->is of->PhysicalType pattern in BIS.

**Comment by diegoalexdiaz** [comment]
Per BWG meeting: Add StructuralAssemblyType and StructuralAccessoryType to the types already included in the PR.
